name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true
          node-version: '20'

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.112.4/hugo_extended_0.112.4_Linux-64bit.tar.gz
          tar -C /tmp -zxvf /tmp/hugo.tar.gz
          mv /tmp/hugo /usr/local/bin/hugo

      - name: Build
        run: hugo

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'harshu6397'
          git config user.email 'harshkumarkardam258@gmail.com'
          git commit -m 'Updated site'
          git push
